using FluentMigrator;
using Serenity.Extensions;

namespace Indotalent.Migrations.DefaultDB
{
	[Migration(20250203152032)]
	public class DefaultDB_20250203_152032_Indotalent_AlterAllTablesWithIsActive : AutoReversingMigration
	{
		public override void Up()
		{

			Alter.Table("AddBalance")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Bill")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("BillDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("BillPayment")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Brand")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("CashBank")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Category")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Colour")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Configuration")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Country")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Customer")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("CustomerContact")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("DueDateReminder")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("DueDateReminderCount")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Exceptions")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Expense")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Flavour")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("HSN")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Invoice")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("InvoiceDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("InvoicePayment")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Languages")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Location")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialIssue")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialIssueDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialRequest")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialRequestDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialRequestStatus")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialRequestStatusMaster")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("MaterialRequestTracking")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("NegativeAdjustment")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("NegativeAdjustmentDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PositiveAdjustment")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PositiveAdjustmentDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Product")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Project")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("ProjectExpense")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("ProjectFund")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("ProjectMaterialRequest")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("ProjectMaterialRequestDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseOrder")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseOrderDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseReceipt")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseReceiptDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseReturn")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseReturnDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("PurchaseTax")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Quotation")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("QuotationDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("RolePermissions")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Roles")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SAC")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesChannel")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesDelivery")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesDeliveryDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesOrder")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesOrderDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesReturn")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesReturnDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("SalesTax")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Shipper")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Size")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("State")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Tax")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Tenant")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("TenantUnitTransaction")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("TransferOrder")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("TransferOrderDetail")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Uom")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("UserPermissions")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("UserPreferences")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("UserProjects")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("UserRoles")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Vendor")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("VendorContact")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);
			Alter.Table("Warehouse")
			   .AddColumn("IsActive").AsBoolean().NotNullable().WithDefaultValue(true);

		}

	}
}